import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { computeSourceHash } from "./source-hash.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, "../dist");
const outDir = join(here, "../../nestjs-doctor/src/report/ui/generated");

const js = readFileSync(join(dist, "report-ui.js"), "utf8");
const css = readFileSync(join(dist, "report-ui.css"), "utf8");

const out = `// Generated by packages/report-ui/scripts/emit-embed.mjs — do not edit.
// Rebuild with: pnpm --filter report-ui build
// source-hash: ${computeSourceHash(join(here, "../src"))}

export const REPORT_UI_JS = ${JSON.stringify(js)};

export const REPORT_UI_CSS = ${JSON.stringify(css)};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "report-ui.generated.ts"), out);
console.log(
	`emit-embed: wrote report-ui.generated.ts (${(out.length / 1024).toFixed(0)} kB)`
);
