#!/usr/bin/env node
// Stamps injection sentinels into dist/index.html and emits it as a TS
// constant consumed by nestjs-doctor's buildHtmlReport.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const DIST_HTML = join(import.meta.dirname, "..", "dist", "index.html");
const TARGET = join(
	import.meta.dirname,
	"..",
	"..",
	"nestjs-doctor",
	"src",
	"report",
	"ui",
	"generated",
	"report-shell.generated.ts"
);

export const DATA_SENTINEL = "<!--ND_REPORT_DATA_SLOT-->";
export const TELEMETRY_SENTINEL = "<!--ND_TELEMETRY_SLOT-->";

let html = readFileSync(DIST_HTML, "utf8");

if (html.includes(DATA_SENTINEL) || html.includes(TELEMETRY_SENTINEL)) {
	throw new Error("emit-embed: sentinels already present in dist/index.html");
}

const headClose = html.indexOf("</head>");
if (headClose === -1) {
	throw new Error("emit-embed: no </head> found in dist/index.html");
}

html =
	html.slice(0, headClose) +
	`${DATA_SENTINEL}${TELEMETRY_SENTINEL}` +
	html.slice(headClose);

mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(
	TARGET,
	"// Generated by packages/report-ui/scripts/emit-embed.mjs — do not edit.\n" +
		"// Contains ND_REPORT_DATA_SLOT and ND_TELEMETRY_SLOT. When replacing a\n" +
		"// sentinel, always pass a function: replace(s, () => value). A plain\n" +
		`// string applies $&/$\`/$' patterns found in artifact source text.\n` +
		`export const REPORT_SHELL_HTML = ${JSON.stringify(html)};\n`
);

console.log(`emit-embed: wrote ${TARGET}`);
